"""Forge Suite — Report Engine.

Generates professional penetration test reports in PDF and HTML from a
list of Finding dicts (as returned by Finding.to_dict()).

Features:
    • VPR-sorted findings table (Critical → High → Medium → Low → Info)
    • CVSS 3.1 and CVSS 4.0 score columns with colour-coded badges
    • Verified redacted evidence derivatives from canonical custody
    • Remediation roadmap section — ordered by VPR priority
    • Executive summary auto-generated by ForgeBrain narrator
    • Appendix: MITRE ATT&CK TTPs, scope, methodology
    • PDF via WeasyPrint; HTML via Jinja2 with inline CSS

FOR AUTHORIZED PENETRATION TESTING AND RED TEAM OPERATIONS ONLY.
"""
from __future__ import annotations

import asyncio
import io
import importlib
import json
import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from common.artifact_io import (
    ArtifactBoundaryError,
    absolute_lexical_path,
    atomic_write_bytes,
    ensure_private_directory,
    read_verified_regular_file,
)
from common.confidence_policy import normalise_finding, should_include_default
from common.evidence import (
    ordinary_evidence_artifacts,
    ordinary_evidence_projection,
    ordinary_finding_projection,
)
from common.redaction import redact_text, redact_value
from common.verification_policy import normalise_finding_truth
from common.version import PRODUCT_LABEL, VERSION

log = logging.getLogger("forge.reporting.engine")


def _ensure_report_directory(path: Path) -> None:
    """Validate/create a no-follow private directory chain."""
    try:
        ensure_private_directory(path)
    except ArtifactBoundaryError as exc:
        if str(exc) == "artifact directory must be a real directory":
            raise ValueError("report directory must be a real directory") from None
        raise ValueError("report directory is unavailable") from None


def _write_private_bytes(path: Path, content: bytes) -> None:
    """Atomically replace a report through a pinned no-follow parent."""
    atomic_write_bytes(path, content, mode=0o600)


def _write_private_text(path: Path, content: str) -> None:
    _write_private_bytes(path, content.encode("utf-8"))

# ── Severity ordering ────────────────────────────────────────────────────────

_SEVERITY_ORDER = {
    "Critical":      0,
    "High":          1,
    "Medium":        2,
    "Low":           3,
    "Informational": 4,
}

_SEVERITY_COLORS = {
    "Critical":      ("#7030A0", "#ffffff"),  # (bg, text)
    "High":          ("#FF0000", "#ffffff"),
    "Medium":        ("#FF9900", "#000000"),
    "Low":           ("#FFFF00", "#000000"),
    "Informational": ("#92D050", "#000000"),
}

_CONFIDENCE_COLORS = {
    "HIGH":       "#27ae60",
    "MEDIUM":     "#f39c12",
    "LOW":        "#e67e22",
    "UNVERIFIED": "#95a5a6",
}


# ── Config dataclass ─────────────────────────────────────────────────────────

_CONFIDENCE_SUPPRESS = {"LOW", "UNVERIFIED"}


@dataclass
class ReportConfig:
    """Configuration for a single report generation run."""
    engagement:     str         = "Untitled Engagement"
    target:         str         = ""
    tester:         str         = PRODUCT_LABEL
    client:         str         = ""
    classification: str         = "CONFIDENTIAL — FOR AUTHORIZED USE ONLY"
    scope:          list[str]   = field(default_factory=list)
    methodology:    list[str]   = field(default_factory=list)
    formats:        list[str]   = field(default_factory=lambda: ["html", "pdf"])
    output_dir:     str         = "."
    include_exec_summary: bool  = True
    include_remediation_roadmap: bool = True
    include_mitre_appendix: bool = True
    include_unverified: bool    = False  # if False, LOW/UNVERIFIED suppressed from default report
    logo_path:      str | None  = None
    include_compliance: bool     = True   # Auto-evaluate PCI DSS / OWASP / ISO 27001
    compliance_collection: Any   = None   # Explicit CollectionEvidence; absent means not tested
    compliance_authority: Any    = None   # Out-of-band signed execution authority

    def __post_init__(self) -> None:
        if not self.methodology:
            self.methodology = [
                "OWASP Testing Guide v4.2",
                "PTES (Penetration Testing Execution Standard)",
                "MITRE ATT&CK Framework",
                "NIST SP 800-115",
            ]


# ── Main engine ──────────────────────────────────────────────────────────────

class ReportEngine:
    """Forge Suite report engine — PDF/HTML report generation.

    Usage::

        engine = ReportEngine(findings, config)
        paths  = await engine.generate()
        # paths = {"html": "/path/report.html", "pdf": "/path/report.pdf"}
    """

    def __init__(
        self,
        findings: list[dict[str, Any]],
        config: ReportConfig,
    ) -> None:
        safe_findings = [
            normalise_finding(ordinary_finding_projection(finding))
            for finding in findings
        ]
        visible = safe_findings if config.include_unverified else [
            f for f in safe_findings if should_include_default(f)
        ]
        # Track suppressed counts for executive summary context
        self._suppressed_count = len(findings) - len(visible)
        self.findings   = sorted(
            visible,
            key=lambda f: (
                -(float(f.get("vpr_score") or f.get("cvss_v31_score") or 0.0)),
                _SEVERITY_ORDER.get(f.get("severity", "Informational"), 99),
            ),
        )
        self.config     = config
        self.output_dir = Path(config.output_dir)
        _ensure_report_directory(self.output_dir)
        self.generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    async def generate(self) -> dict[str, str]:
        """Generate all configured report formats asynchronously.

        Returns:
            Dict mapping format name to absolute output path.
        """
        paths: dict[str, str] = {}

        # Generate executive summary via ForgeBrain narrator (optional)
        exec_summary = ""
        if self.config.include_exec_summary:
            exec_summary = redact_text(await self._generate_exec_summary())

        # Build enriched findings (embed screenshots as b64)
        enriched = self._enrich_findings()

        # Severity summary counts
        summary = self._severity_summary(enriched)

        # Remediation roadmap (sorted by priority)
        roadmap = self._build_remediation_roadmap(enriched) if self.config.include_remediation_roadmap else []

        # MITRE ATT&CK TTP appendix
        mitre_ttps = self._collect_mitre_ttps(enriched) if self.config.include_mitre_appendix else []

        # Caller-supplied binary branding is not embedded in an ordinary
        # report.  Work Package 102 owns validated redacted derivatives.
        logo_b64 = self._load_logo()

        context = {
            "product_label":     PRODUCT_LABEL,
            "product_version":   VERSION,
            "engagement":        redact_text(self.config.engagement),
            "target":            redact_text(self.config.target),
            "tester":            redact_text(self.config.tester),
            "client":            redact_text(self.config.client),
            "classification":    redact_text(self.config.classification),
            "scope":             redact_value(self.config.scope),
            "methodology":       redact_value(self.config.methodology),
            "generated_at":      self.generated_at,
            "findings":          enriched,
            "summary":           summary,
            "exec_summary":      exec_summary,
            "roadmap":           roadmap,
            "mitre_ttps":        mitre_ttps,
            "severity_colors":   _SEVERITY_COLORS,
            "logo_b64":          logo_b64,
            "total_findings":    len(enriched),
            "suppressed_count":  self._suppressed_count,
            "compliance_reports": [],
        }

        # ── Compliance framework evaluation ──────────────────────────────
        if self.config.include_compliance:
            try:
                from common.reporting.compliance_engine import (
                    ComplianceEngine, ComplianceFramework, ComplianceStatus,
                )
                finding_dicts = [f for f in enriched]  # already dict
                c_reports = ComplianceEngine.evaluate_all(
                    finding_dicts,
                    self.config.compliance_collection,
                    self.config.compliance_authority,
                )
                compliance_data = []
                for fw_name, report in c_reports.items():
                    compliance_data.append({
                        "framework": fw_name,
                        "compliance_pct": report.compliance_pct,
                        "coverage_pct": report.coverage_pct,
                        "pass": report.pass_count,
                        "fail": report.fail_count,
                        "partial": report.partial_count,
                        "not_applicable": report.not_applicable_count,
                        "not_tested": report.not_tested_count,
                        "collection_error": report.collection_error_count,
                        "summary": report.summary(),
                        "rules": [r.to_dict() for r in report.results],
                    })
                context["compliance_reports"] = compliance_data
            except Exception:
                log.warning("Compliance evaluation failed")

        if "html" in self.config.formats:
            html_path = self._generate_html(context)
            if html_path:
                paths["html"] = html_path

        if "pdf" in self.config.formats:
            # PDF is derived from HTML — ensure HTML is generated first
            html_path = paths.get("html") or self._generate_html(context)
            pdf_path = self._generate_pdf(html_path)
            if pdf_path:
                paths["pdf"] = pdf_path

        if "json" in self.config.formats:
            json_path = self._generate_json(context)
            if json_path:
                paths["json"] = json_path

        for fmt, path in paths.items():
            log.info("Report generated [%s]: %s", fmt.upper(), path)

        return paths

    # ── HTML generation ───────────────────────────────────────────────────────

    def _generate_html(self, ctx: dict[str, Any]) -> str | None:
        """Render HTML report via Jinja2 (falls back to inline builder)."""
        try:
            from jinja2 import Environment, BaseLoader, select_autoescape
            env = Environment(
                loader=BaseLoader(),
                autoescape=select_autoescape(["html"]),
            )
            template = env.from_string(_HTML_TEMPLATE)
            html = template.render(**ctx)
        except ImportError:
            log.warning("Jinja2 not available — using inline HTML builder")
            html = _build_html_inline(ctx)
        except Exception:
            log.error("HTML template render failed")
            html = _build_html_inline(ctx)

        path = self.output_dir / "report.html"
        _write_private_text(path, redact_text(html))
        return str(path)

    # ── PDF generation ────────────────────────────────────────────────────────

    def _generate_pdf(self, html_path: str | None) -> str | None:
        """Render PDF from pinned HTML bytes without a filename reopen race."""
        if not html_path:
            log.warning("PDF skipped — no HTML source")
            return None
        try:
            expected = absolute_lexical_path(self.output_dir / "report.html")
            selected = absolute_lexical_path(html_path)
            if selected != expected:
                log.warning("PDF skipped — HTML source is outside the report boundary")
                return None
            html_content = read_verified_regular_file(selected)
            weasyprint = importlib.import_module("weasyprint")
            pdf_path = self.output_dir / "report.pdf"
            with io.BytesIO() as artifact:
                weasyprint.HTML(
                    string=html_content.decode("utf-8", errors="replace")
                ).write_pdf(
                    artifact,
                    stylesheets=[weasyprint.CSS(string=_PDF_CSS_OVERRIDE)],
                )
                content = artifact.getvalue()
            _write_private_bytes(pdf_path, content)
            return str(pdf_path)
        except ImportError:
            log.warning("WeasyPrint not installed — PDF generation skipped. "
                        "Install with: pip install weasyprint")
            return None
        except Exception:
            log.error("PDF generation failed")
            return None

    # ── JSON export ───────────────────────────────────────────────────────────

    def _generate_json(self, ctx: dict[str, Any]) -> str | None:
        """Export structured JSON report."""
        out = {
            "product":        ctx["product_label"],
            "product_version": ctx["product_version"],
            "generated_at":   ctx["generated_at"],
            "engagement":     ctx["engagement"],
            "target":         ctx["target"],
            "tester":         ctx["tester"],
            "classification": ctx["classification"],
            "summary":        ctx["summary"],
            "total_findings": ctx["total_findings"],
            "findings":       [
                {
                    k: v
                    for k, v in f.items()
                    if not k.startswith("_") and k != "evidence_artifacts"
                }
                for f in ctx["findings"]
            ],
            "exec_summary":   ctx["exec_summary"],
            "roadmap":        ctx["roadmap"],
            "mitre_ttps":     ctx["mitre_ttps"],
        }
        path = self.output_dir / "report.json"
        _write_private_text(
            path,
            json.dumps(out, indent=2, default=str, ensure_ascii=True),
        )
        return str(path)

    # ── Support helpers ────────────────────────────────────────────────────────

    def _enrich_findings(self) -> list[dict[str, Any]]:
        """Attach verified redacted derivatives and normalise fields."""
        enriched: list[dict[str, Any]] = []
        for i, f in enumerate(self.findings, 1):
            row = dict(f)
            row.update(normalise_finding_truth(row))
            row["_index"] = i
            ev = ordinary_evidence_projection(row.get("evidence"))
            # Ordinary reports omit protected originals and caller paths.
            row["evidence"] = ev
            row["evidence_artifacts"] = ordinary_evidence_artifacts(ev)

            # Severity colour lookup
            sev = f.get("severity", "Informational")
            row["_sev_bg"], row["_sev_fg"] = _SEVERITY_COLORS.get(sev, ("#cccccc", "#000000"))

            # VPR: use stored vpr field, or derive from CVSS score
            cvss = f.get("cvss_v31_score") or 0.0
            row["vpr_score"] = f.get("vpr_score") or cvss or 0.0
            row["vpr_priority"] = f.get("vpr_priority") or f.get("vpr") or _vpr_label(cvss)
            row["_vpr_label"] = row["vpr_priority"]

            # Normalise new first-class fields with safe defaults
            row["url"]          = f.get("url") or f.get("target", "")
            row["verification"] = {
                "confidence": row["confidence"],
                "evidence": [],
            }

            # Confidence badge styling
            row["_conf_color"] = _CONFIDENCE_COLORS.get(row["confidence"], "#888888")

            enriched.append(row)
        return enriched

    def _severity_summary(self, findings: list[dict]) -> dict[str, int]:
        summary = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0, "Informational": 0}
        for f in findings:
            sev = f.get("severity", "Informational")
            summary[sev] = summary.get(sev, 0) + 1
        return summary

    def _build_remediation_roadmap(self, findings: list[dict]) -> list[dict[str, Any]]:
        """Return ordered remediation steps — Critical/High first, grouped by finding."""
        roadmap: list[dict[str, Any]] = []
        seen_remediations: set[str] = set()
        for f in findings:
            rem = f.get("remediation", "").strip()
            if rem and rem not in seen_remediations:
                seen_remediations.add(rem)
                roadmap.append({
                    "priority": len(roadmap) + 1,
                    "title":    f.get("title", "Unknown Finding"),
                    "severity": f.get("severity", "Informational"),
                    "sev_bg":   f.get("_sev_bg", "#cccccc"),
                    "sev_fg":   f.get("_sev_fg", "#000000"),
                    "cvss":     f.get("cvss_v31_score") or 0.0,
                    "vpr_score": f.get("vpr_score") or 0.0,
                    "vpr_priority": f.get("vpr_priority") or f.get("_vpr_label", ""),
                    "remediation": rem,
                    "references":  f.get("references", []),
                })
        return roadmap

    def _collect_mitre_ttps(self, findings: list[dict]) -> list[dict[str, str]]:
        """Deduplicate and describe MITRE ATT&CK TTPs across all findings."""
        seen: dict[str, dict[str, str]] = {}
        for f in findings:
            for ttp in f.get("mitre_attack", []):
                if ttp not in seen:
                    seen[ttp] = {
                        "ttp":     ttp,
                        "title":   f.get("title", ""),
                        "finding": f.get("title", ""),
                    }
        return list(seen.values())

    async def _generate_exec_summary(self) -> str:
        """Auto-generate executive summary via ForgeBrain narrator."""
        try:
            from common.brain.narrator import ReportNarrator
            narrator = ReportNarrator()
            summary = await narrator.executive_summary(
                findings=self.findings,
                engagement=self.config.engagement,
                target=self.config.target,
            )
            return summary or _default_exec_summary(self.findings, self.config)
        except Exception:
            log.debug("ForgeBrain narrator unavailable")
            return _default_exec_summary(self.findings, self.config)

    def _load_logo(self) -> str | None:
        """Keep unvalidated binary files outside ordinary report artifacts."""
        return None


# ── VPR helper ────────────────────────────────────────────────────────────────

def _vpr_label(cvss: float) -> str:
    """Map CVSS score to VPR priority label."""
    if cvss >= 9.0: return "CRITICAL"
    if cvss >= 7.0: return "HIGH"
    if cvss >= 4.0: return "MEDIUM"
    if cvss > 0.0:  return "LOW"
    return "INFO"


# ── Default executive summary (when AI is unavailable) ────────────────────────

def _default_exec_summary(findings: list[dict], config: ReportConfig) -> str:
    """Return a non-authoritative notice for generic report inputs."""

    from common.brain.truth_boundary import advisory_report_projection

    del config
    return advisory_report_projection(
        projection_kind="executive_summary",
        entry_count=len(findings),
    )


# ── HTML template ─────────────────────────────────────────────────────────────

_HTML_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ engagement | e }} — Penetration Test Report</title>
<style>
  :root {
    --primary: #1a1a2e;
    --accent: #e74c3c;
    --accent2: #3498db;
    --bg: #f8f9fa;
    --card: #ffffff;
    --border: #dee2e6;
    --text: #212529;
    --text-secondary: #6c757d;
    --radius: 8px;
    --shadow: 0 2px 8px rgba(0,0,0,0.08);
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', Arial, sans-serif; background: var(--bg);
         color: var(--text); font-size: 14px; line-height: 1.6; }
  .page { max-width: 1200px; margin: 0 auto; padding: 32px 24px; }

  /* Header */
  .report-header { background: var(--primary); color: white; padding: 32px;
                   border-radius: var(--radius); margin-bottom: 24px;
                   display: flex; justify-content: space-between; align-items: center; }
  .report-header h1 { font-size: 1.8rem; font-weight: 700; }
  .report-header .meta { font-size: 0.85rem; opacity: 0.8; margin-top: 8px; }
  .report-header .classification {
    background: var(--accent); padding: 6px 16px; border-radius: 20px;
    font-size: 0.75rem; font-weight: 700; letter-spacing: 1px;
  }

  /* Section headings */
  .section { background: var(--card); border-radius: var(--radius);
              box-shadow: var(--shadow); padding: 24px; margin-bottom: 24px; }
  .section h2 { font-size: 1.1rem; font-weight: 700; color: var(--primary);
                border-bottom: 2px solid var(--accent); padding-bottom: 8px; margin-bottom: 16px; }
  .section h3 { font-size: 0.95rem; font-weight: 600; margin: 12px 0 6px; color: var(--primary); }

  /* Summary badges */
  .summary-grid { display: flex; gap: 12px; flex-wrap: wrap; }
  .sev-badge {
    padding: 10px 20px; border-radius: var(--radius); font-weight: 700;
    font-size: 0.9rem; min-width: 100px; text-align: center;
  }

  /* Findings table */
  table { width: 100%; border-collapse: collapse; }
  th { background: var(--primary); color: white; padding: 10px 12px;
       text-align: left; font-size: 0.82rem; font-weight: 600; }
  td { padding: 10px 12px; border-bottom: 1px solid var(--border);
       vertical-align: top; font-size: 0.85rem; }
  tr:hover td { background: #f1f3f5; }
  .severity-cell { font-weight: 700; text-align: center; border-radius: 4px;
                   padding: 4px 8px; white-space: nowrap; }
  .cvss-score { font-family: monospace; font-weight: 700; }

  /* Finding detail rows */
  .detail-row td { background: #f8f9fa; padding: 16px; }
  .detail-block { margin-bottom: 12px; }
  .detail-block strong { color: var(--text-secondary); font-size: 0.8rem;
                          text-transform: uppercase; letter-spacing: 0.5px; }
  .detail-block p, .detail-block pre { margin-top: 4px; }
  pre { background: #1e1e1e; color: #d4d4d4; padding: 12px; border-radius: 4px;
        font-size: 0.78rem; overflow-x: auto; white-space: pre-wrap; word-break: break-all; }
  ol { margin: 6px 0 0 20px; }
  ol li { margin-bottom: 4px; }

  /* Screenshots */
  .screenshot-container { margin-top: 12px; }
  .screenshot-container img { max-width: 100%; border: 2px solid var(--accent);
                               border-radius: 4px; }

  /* Executive summary */
  .exec-summary { background: #e8f4fd; border-left: 4px solid var(--accent2);
                  padding: 16px; border-radius: 4px; line-height: 1.8; }

  /* Roadmap */
  .roadmap-item { border-left: 4px solid var(--accent); padding: 12px 16px;
                  margin-bottom: 12px; background: #fff8f8; border-radius: 0 4px 4px 0; }
  .roadmap-item h4 { font-size: 0.9rem; margin-bottom: 6px; }
  .roadmap-item p { font-size: 0.85rem; color: var(--text); margin-top: 4px; }

  /* MITRE */
  .ttp-badge { display: inline-block; background: #2c3e50; color: white;
               padding: 3px 8px; border-radius: 3px; font-size: 0.75rem;
               font-family: monospace; margin: 2px; }

  /* Footer */
  .footer { text-align: center; font-size: 0.75rem; color: var(--text-secondary);
             margin-top: 32px; padding-top: 16px; border-top: 1px solid var(--border); }
</style>
</head>
<body>
<div class="page">

  <!-- HEADER -->
  <div class="report-header">
    <div>
      {% if logo_b64 %}<img src="{{ logo_b64 }}" style="height:40px;margin-bottom:12px"><br>{% endif %}
      <h1>Penetration Test Report</h1>
      <div class="meta">
        Engagement: <strong>{{ engagement | e }}</strong> &nbsp;|&nbsp;
        Target: <strong>{{ target | e }}</strong><br>
        Tester: {{ tester | e }} &nbsp;|&nbsp; Generated: {{ generated_at }}
        {% if client %}&nbsp;|&nbsp; Client: {{ client | e }}{% endif %}
      </div>
    </div>
    <div class="classification">{{ classification | e }}</div>
  </div>

  <!-- EXECUTIVE SUMMARY -->
  {% if exec_summary %}
  <div class="section">
    <h2>Executive Summary</h2>
    <div class="exec-summary">{{ exec_summary | e }}</div>
  </div>
  {% endif %}

  <!-- SEVERITY SUMMARY -->
  <div class="section">
    <h2>Risk Summary — {{ total_findings }} Finding(s){% if suppressed_count %} <small style="font-weight:normal;font-size:0.75rem;color:var(--text-secondary)">({{ suppressed_count }} LOW/UNVERIFIED suppressed — use --include-unverified to show all)</small>{% endif %}</h2>
    <div class="summary-grid">
      {% for sev, count in summary.items() %}
      {% set colors = severity_colors[sev] %}
      <div class="sev-badge" style="background:{{ colors[0] }};color:{{ colors[1] }}">
        {{ sev }}<br><span style="font-size:1.4rem">{{ count }}</span>
      </div>
      {% endfor %}
    </div>
  </div>

  <!-- SCOPE & METHODOLOGY -->
  {% if scope or methodology %}
  <div class="section">
    <h2>Scope &amp; Methodology</h2>
    {% if scope %}
    <h3>In-Scope Targets</h3>
    <ul style="margin-left:20px">{% for s in scope %}<li>{{ s | e }}</li>{% endfor %}</ul>
    {% endif %}
    {% if methodology %}
    <h3>Methodology</h3>
    <ul style="margin-left:20px">{% for m in methodology %}<li>{{ m | e }}</li>{% endfor %}</ul>
    {% endif %}
  </div>
  {% endif %}

  <!-- FINDINGS TABLE -->
  <div class="section">
    <h2>Findings</h2>
    <table>
      <thead>
        <tr>
          <th>#</th>
          <th>Vulnerability</th>
          <th>Severity</th>
          <th>CVSS 3.1</th>
          <th>VPR</th>
          <th>CVSS 4.0</th>
          <th>Confidence</th>
          <th>Verification / Proof</th>
          <th>Status</th>
          <th>Target / URL</th>
          <th>Module</th>
        </tr>
      </thead>
      <tbody>
        {% for f in findings %}
        <tr>
          <td>{{ f._index }}</td>
          <td><strong>{{ f.title | e }}</strong></td>
          <td>
            <span class="severity-cell"
                  style="background:{{ f._sev_bg }};color:{{ f._sev_fg }}">
              {{ f.severity | e }}
            </span>
          </td>
          <td class="cvss-score">
            {{ "%.1f"|format(f.cvss_v31_score) if f.cvss_v31_score else "—" }}
          </td>
          <td class="cvss-score">
            {{ "%.1f"|format(f.vpr_score) if f.vpr_score else "—" }}
            {% if f.vpr_priority %}<br><small>{{ f.vpr_priority | e }}</small>{% endif %}
          </td>
          <td class="cvss-score">
            {{ "%.1f"|format(f.cvss_v40_score) if f.cvss_v40_score else "—" }}
          </td>
          <td>
            <span style="background:{{ f._conf_color }};color:#fff;padding:2px 7px;border-radius:3px;font-size:0.75rem;font-weight:700">
              {{ f.confidence | e }}
            </span>
          </td>
          <td>
            <small>{{ f.verification_state | e }}<br>{{ f.proof_type | e }} / {{ f.maturity | e }}</small>
          </td>
          <td><small>{{ f.status | e }}</small></td>
          <td>
            <code style="word-break:break-all">{{ f.url | e }}</code>
            {% if f.port %}<br><small>Port {{ f.port }}</small>{% endif %}
          </td>
          <td><code>{{ f.module | e }}</code></td>
        </tr>
        <tr class="detail-row">
          <td colspan="11">
            <div class="detail-block">
              <strong>Description</strong>
              <p>{{ f.description | e }}</p>
            </div>

            {% if f.reproduction_steps %}
            <div class="detail-block">
              <strong>Reproduction Steps</strong>
              <ol>{% for step in f.reproduction_steps %}<li>{{ step | e }}</li>{% endfor %}</ol>
            </div>
            {% endif %}

            <div class="detail-block">
              <strong>Remediation</strong>
              <p>{{ f.remediation | e }}</p>
            </div>

            <div class="detail-block">
              <strong>Retest verdict</strong>
              <p>{{ f.retest_verdict | default('not_retested', true) | e }}
                 ({{ f.retest_state | default('not_started') | e }})
                 {% if f.retest_reason_code %}
                 — {{ f.retest_reason_code | e }}
                 {% endif %}
              </p>
            </div>

            {% if f.review %}
            <div class="detail-block">
              <strong>Persisted reviewer state</strong>
              <p>Status: {{ f.review.status | e }}<br>
                 Owner: {{ f.review.owner_operator_id | default('Unassigned', true) | e }}<br>
                 Revision: {{ f.review.revision_id | e }} (v{{ f.review.version }})<br>
                 Updated by: {{ f.review.updated_by_operator_id | e }}<br>
                 Notes: {{ f.review.notes | e }}</p>
            </div>
            {% endif %}

            {% if f.canonical_lineage %}
            <div class="detail-block">
              <strong>Locked canonical source lineage</strong>
              <p>Report: {{ f.canonical_lineage.report_id | e }}
                 v{{ f.canonical_lineage.report_version }}<br>
                 Finding: {{ f.canonical_lineage.finding_id | e }}<br>
                 Engagements: {{ f.canonical_lineage.engagement_ids | join(', ') | e }}<br>
                 Jobs: {{ f.canonical_lineage.job_ids | join(', ') | e }}<br>
                 Observations: {{ f.canonical_lineage.observation_ids | join(', ') | e }}<br>
                 Artifacts: {{ f.canonical_lineage.artifact_ids | join(', ') | e }}<br>
                 Retest: {{ f.canonical_lineage.retest_id | e }} /
                 {{ f.canonical_lineage.retest_attempt_id | e }}<br>
                 Reviewer revision: {{ f.canonical_lineage.review_revision_id | e }}<br>
                 Source digest: {{ f.canonical_lineage.source_digest | e }}</p>
            </div>
            {% endif %}

            {% if f.references %}
            <div class="detail-block">
              <strong>References</strong>
              <p>{{ f.references | join(", ") | e }}</p>
            </div>
            {% endif %}

            {% if f.mitre_attack %}
            <div class="detail-block">
              <strong>MITRE ATT&amp;CK</strong><br>
              {% for ttp in f.mitre_attack %}
              <span class="ttp-badge">{{ ttp | e }}</span>
              {% endfor %}
            </div>
            {% endif %}

            {% for artifact in f.evidence_artifacts %}
            <div class="detail-block">
              <strong>Evidence derivative ({{ artifact.capture_kind | e }})</strong>
              <pre>{{ artifact.derivative | e }}</pre>
            </div>
            {% endfor %}

            {% if f.verification %}
            <div class="detail-block" style="margin-top:8px;padding:8px;background:#f0f7ff;border-left:3px solid {{ f._conf_color }};border-radius:0 4px 4px 0">
              <strong style="font-size:0.75rem;text-transform:uppercase;color:var(--text-secondary)">FP Verification</strong><br>
              <small>
                Confidence: <span style="color:{{ f._conf_color }};font-weight:700">{{ f.confidence | e }}</span>
                &nbsp;|&nbsp; Probes: {{ f.verification.get('probe_hits', 0) }}/{{ f.verification.get('probe_count', 0) }}
                {% if f.verification.get('baseline_time') %}
                &nbsp;|&nbsp; Baseline: {{ "%.2f"|format(f.verification.baseline_time) }}s
                {% endif %}
                {% if f.verification.get('evidence') %}
                <br>{{ f.verification.evidence | join(' &mdash; ') | e | truncate(300) }}
                {% endif %}
                {% if f.verification.get('error') %}
                <br><span style="color:#e74c3c">Error: {{ f.verification.error | e }}</span>
                {% endif %}
              </small>
            </div>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <!-- REMEDIATION ROADMAP -->
  {% if roadmap %}
  <div class="section">
    <h2>Remediation Roadmap (Priority Order)</h2>
    {% for item in roadmap %}
    <div class="roadmap-item">
      <h4>
        #{{ item.priority }}
        <span class="severity-cell"
              style="background:{{ item.sev_bg }};color:{{ item.sev_fg }};padding:2px 8px;font-size:0.75rem">
          {{ item.severity | e }}
        </span>
        {{ item.title | e }}
        {% if item.cvss %}&nbsp;<small style="color:var(--text-secondary)">(CVSS {{ "%.1f"|format(item.cvss) }})</small>{% endif %}
      </h4>
      <p>{{ item.remediation | e }}</p>
      {% if item.references %}
      <small style="color:var(--text-secondary)">References: {{ item.references | join(", ") | e }}</small>
      {% endif %}
    </div>
    {% endfor %}
  </div>
  {% endif %}

  <!-- MITRE ATT&CK APPENDIX -->
  {% if mitre_ttps %}
  <div class="section">
    <h2>Appendix — MITRE ATT&amp;CK TTPs Observed</h2>
    <div style="margin-top:8px">
      {% for ttp in mitre_ttps %}
      <span class="ttp-badge" title="{{ ttp.finding | e }}">{{ ttp.ttp | e }}</span>
      {% endfor %}
    </div>
    <p style="margin-top:12px;font-size:0.82rem;color:var(--text-secondary)">
      Reference: <a href="https://attack.mitre.org" target="_blank">https://attack.mitre.org</a>
    </p>
  </div>
  {% endif %}

  <div class="footer">
    Generated by {{ product_label | e }} — FOR AUTHORIZED PENETRATION TESTING USE ONLY<br>
    {{ generated_at }} &nbsp;|&nbsp; {{ classification | e }}
  </div>

</div>
</body>
</html>"""


def _build_compliance_html(compliance_reports: list[dict]) -> str:
    """Build HTML section for compliance framework evaluation results."""
    if not compliance_reports:
        return ""

    _STATUS_ICONS = {
        "pass": ("✅", "#27ae60", "#e8f5e9"),
        "fail": ("❌", "#e74c3c", "#fce4ec"),
        "partial": ("⚠️", "#f39c12", "#fff8e1"),
        "not_applicable": ("➖", "#607d8b", "#eceff1"),
        "not_tested": ("⬜", "#95a5a6", "#f5f5f5"),
        "collection_error": ("⛔", "#c0392b", "#fdecea"),
    }

    sections = []
    for report in compliance_reports:
        fw_name = _escape(report.get("framework", ""))
        pct = report.get("compliance_pct", 0)
        pass_c = report.get("pass", 0)
        fail_c = report.get("fail", 0)
        partial_c = report.get("partial", 0)
        na_c = report.get("not_applicable", 0)
        nt_c = report.get("not_tested", 0)
        error_c = report.get("collection_error", 0)
        coverage_pct = report.get("coverage_pct", 0)

        # Gauge color
        if pct >= 80:
            gauge_color = "#27ae60"
        elif pct >= 50:
            gauge_color = "#f39c12"
        else:
            gauge_color = "#e74c3c"

        rules_html = ""
        for rule in report.get("rules", []):
            status = str(rule.get("status", "not_tested")).lower()
            icon, color, bg = _STATUS_ICONS.get(status, ("?", "#999", "#f5f5f5"))
            finding_count = rule.get("finding_count", 0)
            finding_titles = ", ".join(rule.get("finding_titles", [])[:3])
            collection = rule.get("collection") or {}
            collection_status = collection.get("status", "not_recorded")
            collector = (
                f"{collection.get('collector_id', 'unknown')}@"
                f"{collection.get('collector_version', 'unknown')}"
            )
            check = (
                f"{collection.get('check_id', 'unknown')}@"
                f"{collection.get('check_version', 'unknown')}"
            )
            reason = rule.get("reason", "")
            proof_type = rule.get("proof_type", "unknown")
            rules_html += f"""
            <tr style="background:{bg}">
                <td style="font-family:monospace;font-weight:700">{_escape(rule.get('rule_id', ''))}</td>
                <td>{_escape(rule.get('title', ''))}</td>
                <td style="text-align:center;font-size:16px">{icon}</td>
                <td style="color:{color};font-weight:700">{status}</td>
                <td>{finding_count}</td>
                <td style="font-size:11px">{_escape(finding_titles)}</td>
                <td style="font-size:11px">{_escape(reason)}</td>
                <td style="font-size:11px">{_escape(str(collection_status))}<br>{_escape(collector)}<br>{_escape(check)}</td>
                <td style="font-size:11px">{_escape(str(proof_type))}</td>
                <td style="font-size:11px">{_escape(rule.get('remediation', ''))[:100]}</td>
            </tr>"""

        sections.append(f"""
        <div style="margin-bottom:30px;border:1px solid #ddd;border-radius:8px;overflow:hidden">
            <div style="background:#2c3e50;color:#fff;padding:12px 16px;display:flex;justify-content:space-between;align-items:center">
                <h3 style="margin:0">{fw_name}</h3>
                <div style="display:flex;gap:12px;align-items:center">
                    <span style="background:{gauge_color};color:#fff;padding:4px 12px;border-radius:12px;font-weight:700;font-size:16px">Compliance {pct}% / Coverage {coverage_pct}%</span>
                    <span>✅ {pass_c} &nbsp; ❌ {fail_c} &nbsp; ⚠️ {partial_c} &nbsp; ➖ {na_c} &nbsp; ⬜ {nt_c} &nbsp; ⛔ {error_c}</span>
                </div>
            </div>
            <table style="width:100%;border-collapse:collapse">
                <thead>
                    <tr style="background:#ecf0f1">
                        <th style="padding:8px;text-align:left">Rule ID</th>
                        <th style="padding:8px;text-align:left">Requirement</th>
                        <th style="padding:8px;text-align:center">Status</th>
                        <th style="padding:8px;text-align:left">Result</th>
                        <th style="padding:8px;text-align:left">Findings</th>
                        <th style="padding:8px;text-align:left">Matched</th>
                        <th style="padding:8px;text-align:left">Reason</th>
                        <th style="padding:8px;text-align:left">Collection</th>
                        <th style="padding:8px;text-align:left">Proof</th>
                        <th style="padding:8px;text-align:left">Remediation</th>
                    </tr>
                </thead>
                <tbody>{rules_html}</tbody>
            </table>
        </div>""")

    return f"""
    <h2 style="border-bottom:2px solid #2c3e50;padding-bottom:8px;margin-top:40px">
        Compliance Assessment
    </h2>
    <p style="color:#666;margin-bottom:20px">
        Evidence-state mapping for assessment review; this is not an attestation.
        A pass requires versioned applicability, successful collection, and supported proof.
    </p>
    {"".join(sections)}
    """


# ── PDF CSS override (WeasyPrint page sizing) ─────────────────────────────────

_PDF_CSS_OVERRIDE = """
@page {
    size: A4;
    margin: 20mm 18mm 20mm 18mm;
}
body {
    font-size: 11px;
}
.report-header {
    -weasyprint-avoid-page-break-inside: always;
}
tr.detail-row {
    page-break-inside: avoid;
}
"""


# ── Inline HTML fallback (no Jinja2) ─────────────────────────────────────────

def _escape(text: str) -> str:
    return (str(text)
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;"))


def _build_html_inline(ctx: dict[str, Any]) -> str:
    """Minimal fallback HTML builder (no Jinja2 dependency)."""
    findings = ctx["findings"]
    summary  = ctx["summary"]

    sev_bars = "".join(
        f'<span style="background:{ctx["severity_colors"][sev][0]};color:{ctx["severity_colors"][sev][1]};'
        f'padding:8px 16px;margin:4px;border-radius:6px;font-weight:700;display:inline-block">'
        f'{_escape(sev)}: {count}</span>'
        for sev, count in summary.items()
    )

    rows_html = ""
    for f in findings:
        sev_bg, sev_fg = f.get("_sev_bg", "#ccc"), f.get("_sev_fg", "#000")
        cvss31 = f"{ f.get('cvss_v31_score', 0.0):.1f}" if f.get("cvss_v31_score") else "—"
        cvss40 = f"{ f.get('cvss_v40_score', 0.0):.1f}" if f.get("cvss_v40_score") else "—"
        vpr = f"{ f.get('vpr_score', 0.0):.1f}" if f.get("vpr_score") else "—"
        confidence = _escape(f.get("confidence", "UNVERIFIED"))
        status = _escape(f.get("status", "open"))
        verification_state = _escape(f.get("verification_state", "unknown"))
        proof_type = _escape(f.get("proof_type", "unknown"))
        maturity = _escape(f.get("maturity", "experimental"))
        steps  = "".join(f"<li>{_escape(s)}</li>" for s in f.get("reproduction_steps", []))
        refs   = _escape(", ".join(f.get("references", [])))
        mitre  = " ".join(
            f'<span style="background:#2c3e50;color:#fff;padding:2px 6px;font-size:11px;border-radius:3px;">{_escape(t)}</span>'
            for t in f.get("mitre_attack", [])
        )
        evidence_html = "".join(
            (
                "<br><strong>Evidence derivative "
                f"({_escape(artifact['capture_kind'])}):</strong>"
                f"<pre>{_escape(artifact['derivative'])}</pre>"
            )
            for artifact in f.get("evidence_artifacts", [])
        )
        review = f.get("review") if isinstance(f.get("review"), dict) else {}
        review_html = ""
        if review:
            review_html = (
                "<br><strong>Persisted reviewer state:</strong> "
                f"status={_escape(review.get('status', ''))}; "
                f"owner={_escape(review.get('owner_operator_id') or 'Unassigned')}; "
                f"revision={_escape(review.get('revision_id', ''))}; "
                f"updated_by={_escape(review.get('updated_by_operator_id', ''))}; "
                f"notes={_escape(review.get('notes', ''))}"
            )
        lineage = (
            f.get("canonical_lineage")
            if isinstance(f.get("canonical_lineage"), dict)
            else {}
        )
        lineage_html = ""
        if lineage:
            lineage_html = (
                "<br><strong>Locked canonical source lineage:</strong> "
                + _escape(
                    json.dumps(
                        lineage,
                        sort_keys=True,
                        separators=(",", ":"),
                        ensure_ascii=True,
                    )
                )
            )

        rows_html += f"""
        <tr>
          <td>{f['_index']}</td>
          <td><strong>{_escape(f.get('title',''))}</strong></td>
          <td style="background:{sev_bg};color:{sev_fg};text-align:center;font-weight:700">{_escape(f.get('severity',''))}</td>
          <td style="font-family:monospace">{cvss31}</td>
          <td style="font-family:monospace">{vpr}<br><small>{_escape(f.get('vpr_priority',''))}</small></td>
          <td style="font-family:monospace">{cvss40}</td>
          <td><code>{confidence}</code></td>
          <td><code>{verification_state}</code><br><small>{proof_type} / {maturity}</small></td>
          <td><small>{status}</small></td>
          <td><code>{_escape(f.get('url') or f.get('target',''))}</code></td>
          <td><code>{_escape(f.get('module',''))}</code></td>
        </tr>
        <tr><td colspan="11" style="background:#f9f9f9;padding:14px">
          <strong>Description:</strong> {_escape(f.get('description',''))}<br><br>
          <strong>Reproduction:</strong><ol>{steps}</ol>
          <strong>Remediation:</strong> {_escape(f.get('remediation',''))}<br>
          <strong>References:</strong> {refs}<br>
          <strong>MITRE ATT&CK:</strong> {mitre}
          {review_html}
          {lineage_html}
          {evidence_html}
        </td></tr>"""

    return f"""<!DOCTYPE html><html lang="en"><head>
<meta charset="UTF-8"><title>{_escape(ctx['engagement'])} Report</title>
<style>
body{{font-family:Arial,sans-serif;margin:0;padding:20px;background:#f5f5f5}}
h1{{color:#333;border-bottom:3px solid #e74c3c;padding-bottom:10px}}
table{{width:100%;border-collapse:collapse;background:#fff;border-radius:6px}}
th{{background:#2c3e50;color:#fff;padding:10px;text-align:left}}
td{{padding:8px 10px;border-bottom:1px solid #eee;vertical-align:top}}
tr:hover td{{background:#f0f0f0}}pre{{background:#1e1e1e;color:#d4d4d4;padding:8px;overflow:auto}}
</style></head><body>
<h1>Penetration Test Report — {_escape(ctx['engagement'])}</h1>
<p><strong>Target:</strong> {_escape(ctx['target'])} | <strong>Tester:</strong> {_escape(ctx['tester'])} | <strong>Generated:</strong> {_escape(ctx['generated_at'])}</p>
<div style="margin:16px 0">{sev_bars}</div>
<h2 style="border-bottom:2px solid #e74c3c;padding-bottom:8px">Findings</h2>
<table><thead><tr><th>#</th><th>Vulnerability</th><th>Severity</th><th>CVSS 3.1</th><th>VPR</th><th>CVSS 4.0</th><th>Confidence</th><th>Verification / Proof</th><th>Status</th><th>Target</th><th>Module</th></tr></thead>
<tbody>{rows_html}</tbody></table>
<p style="color:#999;font-size:11px;margin-top:20px">Generated by {_escape(ctx['product_label'])} — FOR AUTHORIZED USE ONLY</p>
{_build_compliance_html(ctx.get('compliance_reports', []))}
</body></html>"""


# ── Tests ─────────────────────────────────────────────────────────────────────

class TestReportEngine:
    """Unit tests for report engine."""

    def _sample_findings(self) -> list[dict]:
        return [
            {
                "id": "a1", "title": "SQL Injection", "severity": "Critical",
                "cvss_v31_score": 9.8, "cvss_v31_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
                "cvss_v40_score": 9.3, "target": "https://example.com", "port": 443,
                "service": "https", "module": "sqli_scanner",
                "description": "SQL injection found in login form.",
                "reproduction_steps": ["Navigate to /login", "Inject ' OR 1=1--"],
                "remediation": "Use parameterized queries.",
                "references": ["CWE-89", "OWASP A03:2021"],
                "mitre_attack": ["T1190"],
                "discovered_at": "2026-06-20T00:00:00Z",
                "evidence": {"observations": [], "state": "unavailable"},
                "operator_confirmed": False, "tags": [],
                "confidence": "HIGH", "status": "open", "vpr": "CRITICAL",
                "verification_state": "unknown", "proof_type": "unknown",
                "maturity": "experimental",
                "url": "https://example.com/login", "verification": None,
            },
            {
                "id": "b2", "title": "Missing HSTS Header", "severity": "Medium",
                "cvss_v31_score": 5.4, "cvss_v31_vector": "",
                "cvss_v40_score": None, "target": "https://example.com",
                "module": "header_audit", "description": "HSTS not set.",
                "reproduction_steps": ["Check response headers"],
                "remediation": "Add Strict-Transport-Security header.",
                "references": ["OWASP"], "mitre_attack": [],
                "discovered_at": "2026-06-20T00:00:00Z",
                "evidence": {}, "operator_confirmed": False, "tags": [],
                "confidence": "MEDIUM", "status": "open", "vpr": "MEDIUM",
                "url": None, "verification": None,
            },
        ]

    def test_severity_sort(self) -> None:
        import asyncio, tempfile
        config = ReportConfig(output_dir=tempfile.mkdtemp())
        engine = ReportEngine(self._sample_findings(), config)
        assert engine.findings[0]["severity"] == "Critical"

    def test_severity_summary(self) -> None:
        import asyncio, tempfile
        config = ReportConfig(output_dir=tempfile.mkdtemp())
        engine = ReportEngine(self._sample_findings(), config)
        enriched = engine._enrich_findings()
        summary = engine._severity_summary(enriched)
        assert summary["Critical"] == 1
        assert summary["Medium"] == 1

    def test_vpr_label(self) -> None:
        assert _vpr_label(9.8) == "CRITICAL"
        assert _vpr_label(7.5) == "HIGH"
        assert _vpr_label(5.0) == "MEDIUM"
        assert _vpr_label(2.0) == "LOW"
        assert _vpr_label(0.0) == "INFO"

    def test_default_exec_summary(self) -> None:
        config = ReportConfig(engagement="Test", target="example.com")
        summary = _default_exec_summary(self._sample_findings(), config)
        assert "Advisory projection only" in summary
        assert "not published as execution" in summary
        assert "example.com" not in summary
        assert "CRITICAL" not in summary

    def test_generate_html(self) -> None:
        import asyncio, tempfile
        tmpdir = tempfile.mkdtemp()
        config = ReportConfig(output_dir=tmpdir, formats=["html"])
        engine = ReportEngine(self._sample_findings(), config)
        paths = asyncio.run(engine.generate())
        assert "html" in paths
        html_content = Path(paths["html"]).read_text()
        assert "SQL Injection" in html_content
        assert "<!DOCTYPE html>" in html_content

    def test_roadmap_ordering(self) -> None:
        import tempfile
        config = ReportConfig(output_dir=tempfile.mkdtemp())
        engine = ReportEngine(self._sample_findings(), config)
        enriched = engine._enrich_findings()
        roadmap = engine._build_remediation_roadmap(enriched)
        assert len(roadmap) >= 1
        assert "parameterized" in roadmap[0]["remediation"]
