#!/usr/bin/env python3
"""Verify that every shipped product surface derives one canonical release version."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SEMVER_RE = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+$")
HARDCODED_PRODUCT_VERSION_RE = re.compile(
    r"\bForge(?: Suite|-Suite)(?:\s+v|/)[0-9]+(?:\.[0-9]+){0,2}\b"
)


class VersionValidationError(RuntimeError):
    """Raised when a release-identity surface drifts from VERSION."""


def _read(root: Path, relative_path: str) -> str:
    path = root / relative_path
    if not path.is_file():
        raise VersionValidationError(f"required version surface is missing: {relative_path}")
    return path.read_text(encoding="utf-8")


def _require(source: str, fragment: str, label: str) -> None:
    if fragment not in source:
        raise VersionValidationError(f"{label}: missing canonical version binding {fragment!r}")


def _reject_hardcoded_product_versions(source: str, label: str) -> None:
    """Reject release identities without treating protocol/schema versions as product drift."""
    matches = sorted(set(HARDCODED_PRODUCT_VERSION_RE.findall(source)))
    if matches:
        raise VersionValidationError(
            f"{label}: hardcoded product release identity remains: {', '.join(matches)}"
        )


def validate_repository(root: Path = ROOT) -> str:
    version = _read(root, "VERSION").strip()
    if not SEMVER_RE.fullmatch(version):
        raise VersionValidationError("VERSION must contain exactly one semantic version")

    version_module = _read(root, "common/version.py")
    _require(version_module, ' / "VERSION"', "common/version.py")
    _require(version_module, "VERSION = _VERSION_FILE.read_text", "common/version.py")
    _require(
        version_module,
        'PRODUCT_USER_AGENT = f"Forge-Suite/{VERSION}"',
        "common/version.py",
    )

    forge = _read(root, "forge.py")
    _require(forge, "from common.version import VERSION", "forge.py")
    _require(forge, 'description=f"Forge Suite v{VERSION} APEX', "forge.py")
    _require(forge, 'version=f"Forge Suite v{VERSION}"', "forge.py")
    if 'description="Forge Suite v5' in forge:
        raise VersionValidationError("forge.py retains a hardcoded major-version description")

    engines = {
        "webforge/webforge.py": "WebForge",
        "netforge/netforge.py": "NetForge",
        "adforge/adforge.py": "ADForge",
        "aiforge/aiforge.py": "AIForge",
    }
    for relative_path, product in engines.items():
        source = _read(root, relative_path)
        _require(source, "from common.version import VERSION", relative_path)
        _require(source, f'version=f"{product} {{VERSION}}"', relative_path)

    dashboard = _read(root, "common/dashboard/server.py")
    _require(dashboard, "from common.version import PRODUCT_LABEL, VERSION", "dashboard API")
    health_section = dashboard.split('@app.get("/api/v1/health")', 1)
    if len(health_section) != 2 or '"version": VERSION' not in health_section[1][:1200]:
        raise VersionValidationError("dashboard health API does not return canonical VERSION")

    report_engine = _read(root, "common/reporting/report_engine.py")
    _require(report_engine, '"product_version":   VERSION', "common report engine")
    report_surfaces = {
        "aiforge/modules/reporting/html_report.py": "Generated by AIForge v{VERSION}",
        "aiforge/modules/reporting/pdf_report.py": "Generated by AIForge v{VERSION}",
        "netforge/modules/reporting/html_report.py": "Generated by NetForge v{VERSION}",
        "netforge/modules/reporting/pdf_report.py": "Generated by NetForge v{VERSION}",
    }
    for relative_path, fragment in report_surfaces.items():
        source = _read(root, relative_path)
        _require(source, "from common.version import VERSION", relative_path)
        _require(source, fragment, relative_path)
    for stale in ("AIForge v1.0.0", "NetForge v5 APEX"):
        if any(stale in _read(root, path) for path in report_surfaces):
            raise VersionValidationError(f"report surface retains stale release identity {stale!r}")

    runtime_identity_surfaces = {
        "common/intel/technique_learner.py": (
            "from common.version import PRODUCT_USER_AGENT",
            "TECHNIQUE_LEARNER_USER_AGENT = (",
            'f"{PRODUCT_USER_AGENT} IntelPipeline (TechniqueLearner)"',
            '"User-Agent": TECHNIQUE_LEARNER_USER_AGENT',
        ),
        "common/intel/nuclei_sync.py": (
            "from common.version import PRODUCT_USER_AGENT",
            'NUCLEI_SYNC_USER_AGENT = f"{PRODUCT_USER_AGENT} IntelPipeline (NucleiSync)"',
            '"User-Agent": NUCLEI_SYNC_USER_AGENT',
        ),
        "common/brain/brain.py": (
            "from common.version import PRODUCT_LABEL",
            'f"You are ForgeBrain, the AI reasoning engine for {PRODUCT_LABEL} — "',
        ),
    }
    for relative_path, required_fragments in runtime_identity_surfaces.items():
        source = _read(root, relative_path)
        for fragment in required_fragments:
            _require(source, fragment, relative_path)
        _reject_hardcoded_product_versions(source, relative_path)

    package = json.loads(_read(root, "apex-ui/package.json"))
    lock = json.loads(_read(root, "apex-ui/package-lock.json"))
    if package.get("version") != version:
        raise VersionValidationError("apex-ui/package.json version differs from VERSION")
    if lock.get("version") != version or (lock.get("packages") or {}).get("", {}).get("version") != version:
        raise VersionValidationError("apex-ui/package-lock.json root version differs from VERSION")
    expected_tools = {"node": "20.19.5", "npm": "10.8.2"}
    if package.get("engines") != expected_tools or package.get("packageManager") != "npm@10.8.2":
        raise VersionValidationError("frontend release identity lacks the qualified Node/npm tuple")
    vite = _read(root, "apex-ui/vite.config.js")
    _require(vite, "../VERSION", "Vite config")
    _require(vite, "__FORGE_VERSION__", "Vite config")
    app = _read(root, "apex-ui/src/App.jsx")
    _require(app, "FORGE_UI_VERSION = __FORGE_VERSION__", "Apex UI")

    dockerfile = _read(root, "Dockerfile")
    _require(dockerfile, "ARG FORGE_VERSION", "Dockerfile")
    _require(dockerfile, 'org.opencontainers.image.version="${FORGE_VERSION}"', "Dockerfile")
    _require(dockerfile, 'tr -d \'\\r\\n\' < VERSION', "Dockerfile")
    makefile = _read(root, "Makefile")
    _require(makefile, "FORGE_VERSION :=", "Makefile")
    _require(makefile, "< VERSION", "Makefile")
    _require(makefile, 'printf \'%s\\n\' "$(FORGE_VERSION)"', "Makefile")
    return version


def validate_runtime_outputs(root: Path, version: str) -> None:
    commands = {
        "forge.py": f"Forge Suite v{version}",
        "webforge/webforge.py": f"WebForge {version}",
        "netforge/netforge.py": f"NetForge {version}",
        "adforge/adforge.py": f"ADForge {version}",
        "aiforge/aiforge.py": f"AIForge {version}",
    }
    for relative_path, expected in commands.items():
        completed = subprocess.run(
            [sys.executable, relative_path, "--version"],
            cwd=root,
            check=False,
            capture_output=True,
            text=True,
            timeout=30,
        )
        output = completed.stdout.strip()
        if completed.returncode or output != expected:
            raise VersionValidationError(
                f"{relative_path} --version expected {expected!r}; "
                f"exit={completed.returncode} stdout={output!r} stderr={completed.stderr.strip()!r}"
            )
    make_output = subprocess.run(
        ["make", "-s", "version"],
        cwd=root,
        check=False,
        capture_output=True,
        text=True,
        timeout=30,
    )
    if make_output.returncode or make_output.stdout.strip() != version:
        raise VersionValidationError("make version does not emit canonical VERSION")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--static-only", action="store_true")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    try:
        version = validate_repository(root)
        if not args.static_only:
            validate_runtime_outputs(root, version)
    except (OSError, json.JSONDecodeError, subprocess.SubprocessError, VersionValidationError) as exc:
        print(f"FAIL product-version: {exc}", file=sys.stderr)
        return 1
    print(f"PASS product-version version={version} dynamic={str(not args.static_only).lower()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
