import React from 'react';
import TopBar from '../components/TopBar';
import Card from '../components/Card';
import Button from '../components/Button';
import Badge from '../components/Badge';
import { FileText, Shield, FileCheck, Sliders, Download, TrendingUp } from 'lucide-react';

const fmtColor = (fmt) => fmt === 'PDF' ? 'critical' : fmt === 'HTML' ? 'info' : 'medium';

const Reports = () => {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
      <TopBar
        title="Report Generation"
        subtitle="Generate executive summaries, technical deep-dives, and compliance reports"
        actions={
          <>
            <Button variant="secondary">SCHEDULE REPORT</Button>
            <Button variant="primary">+ NEW REPORT</Button>
          </>
        }
      />
      <div style={{ padding: '18px 32px', display: 'flex', flexDirection: 'column', gap: '14px', flex: 1, overflowY: 'auto' }}>

        {/* ROW 0: Stats */}
        <div style={{ display: 'flex', gap: '14px' }}>
          {[
            { label: 'TOTAL REPORTS', value: '0', icon: FileText, color: 'var(--color-info)' },
            { label: 'THIS MONTH', value: '0', icon: TrendingUp, color: 'var(--color-success)' },
            { label: 'PDF', value: '0', icon: Download, color: 'var(--color-critical)' },
            { label: 'HTML / DOCX', value: '0', icon: FileCheck, color: 'var(--color-medium)' },
          ].map(stat => (
            <Card key={stat.label} style={{ flex: 1 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                <div>
                  <div className="font-mono text-muted" style={{ fontSize: '10px' }}>{stat.label}</div>
                  <div className="font-heading" style={{ fontSize: '32px', fontWeight: 600, color: stat.color, marginTop: '4px' }}>{stat.value}</div>
                </div>
                <div style={{ padding: '8px', borderRadius: '8px', backgroundColor: 'var(--bg-input)' }}>
                  <stat.icon size={20} color={stat.color} />
                </div>
              </div>
            </Card>
          ))}
        </div>

        {/* ROW 1: Template Cards */}
        <div style={{ display: 'flex', gap: '14px' }}>
          {[
            { title: 'Executive Summary', icon: <FileText size={24} color="var(--color-critical)" />, desc: 'High-level risk overview for management & board', bg: 'rgba(255,68,68,0.05)', border: 'rgba(255,68,68,0.2)' },
            { title: 'Technical Deep-Dive', icon: <Shield size={24} color="var(--color-info)" />, desc: 'Full findings with PoC, payloads, and remediation steps', bg: 'rgba(41,121,255,0.05)', border: 'rgba(41,121,255,0.2)' },
            { title: 'Compliance Report', icon: <FileCheck size={24} color="var(--color-medium)" />, desc: 'OWASP, PCI-DSS, ISO 27001 compliance mapping', bg: 'rgba(255,196,0,0.05)', border: 'rgba(255,196,0,0.2)' },
            { title: 'Custom Builder', icon: <Sliders size={24} color="var(--color-success)" />, desc: 'Drag-and-drop report builder with custom sections', bg: 'rgba(0,200,83,0.05)', border: 'rgba(0,200,83,0.2)' }
          ].map(tpl => (
            <div key={tpl.title} style={{ flex: 1, display: 'flex' }} className="report-card">
              <Card style={{ flex: 1, alignItems: 'center', textAlign: 'center', borderTop: `2px solid ${tpl.border}`, transition: 'all 0.2s', cursor: 'pointer' }}>
                <div style={{ marginBottom: '16px', padding: '16px', borderRadius: '50%', backgroundColor: tpl.bg }}>{tpl.icon}</div>
                <h3 style={{ fontSize: '16px', fontWeight: 600, marginBottom: '8px', color: 'var(--text-primary)' }}>{tpl.title}</h3>
                <p className="text-muted" style={{ fontSize: '12px', marginBottom: '16px', lineHeight: 1.5, flex: 1 }}>{tpl.desc}</p>
                <Button variant="secondary" style={{ width: '100%', borderColor: tpl.border }}>Generate &rarr;</Button>
              </Card>
            </div>
          ))}
        </div>

        {/* ROW 2: Generated Reports Table */}
        <Card title="Generated Reports" style={{ flex: 1 }} noPadding>
          <table>
            <thead>
              <tr>
                <th>Report ID</th>
                <th>Title</th>
                <th>Format</th>
                <th>Date</th>
                <th>Generated By</th>
                <th>Size</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td colSpan={7} style={{ textAlign: 'center', padding: '48px 0', color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', fontSize: '12px' }}>
                  No reports generated yet — select a template above to begin
                </td>
              </tr>
            </tbody>
          </table>
        </Card>
      </div>
      <style>{`
        .report-card:hover > div {
          transform: translateY(-4px);
          box-shadow: 0 8px 24px rgba(0,0,0,0.4);
        }
      `}
      </style>
    </div>
  );
};

export default Reports;
